# Generated by Django 5.0.7 on 2024-07-23 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('location', models.CharField(max_length=100)),
                ('headliner_band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.band')),
                ('supporting_bands', models.ManyToManyField(related_name='supporting_concert', to='concerts.band')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.venue')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
