# Generated by Django 5.0.6 on 2024-07-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={},
        ),
        migrations.RemoveField(
            model_name='concert',
            name='location',
        ),
    ]
